
#export ZDOTDIR=~/my-settings/


PATH=$HOME/bin:/usr/local/bin:$PATH
PAGER=less
COLORTERM=yes
HISTFILE=$HOME/.zshhistory
HISTSIZE=1000
SAVEHIST=500000
DIRSTACKSIZE=20
PYTHONSTARTUP=$HOME/.pystartup
WORKON_HOME=~/.virtualenvs/
export PATH PAGER COLORTERM HISTFILE HISTSIZE SAVEHIST DIRSTACKSIZE PYTHONSTARTUP WORKON_HOME
